locators and first test case
whichfinder/automation_study pull request #11
Opened 2019-12-13 09:40 UTC by dimahadgi

2019-12-13 12:57 UTC, whichfinder commented on src/locators/main_page_locators.py
> +SHARED = (By.XPATH, '//button/span[text()="Shared"]')
also possible to search via css g path[d*="M11,12"]

2019-12-13 12:57 UTC, whichfinder commented on src/locators/main_page_locators.py
> +CREATE_WORKER_BUTTON = (By.XPATH, '//button/span[text()="Create"]')
div[role="dialog"] button[tabindex="0"]

2019-12-13 12:57 UTC, whichfinder commented on src/locators/main_page_locators.py
> +LAST_NAME_FIELD = (By.CSS_SELECTOR, 'form div #lastname')
remove div

2019-12-13 13:02 UTC, dimahadgi commented on src/locators/main_page_locators.py
> +SHARED = (By.XPATH, '//button/span[text()="Shared"]')
replace xpath to css

2019-12-13 13:14 UTC, dimahadgi commented on src/locators/main_page_locators.py
> +CREATE_WORKER_BUTTON = (By.XPATH, '//button/span[text()="Create"]')
For all active buttons tabindex = 0

2019-12-13 13:15 UTC, dimahadgi commented on src/locators/main_page_locators.py
> +LAST_NAME_FIELD = (By.CSS_SELECTOR, 'form div #lastname')
div removed

2019-12-20 10:12 UTC, whichfinder requested changes

2019-12-20 10:12 UTC, whichfinder commented on src/pages/login_page.py
> +
remove try except

2019-12-20 10:12 UTC, whichfinder commented on src/pages/main_page.py
> +import time
import order

2019-12-20 10:12 UTC, whichfinder commented on src/pages/main_page.py
> +            EC.element_to_be_clickable(locators.SEARCH))
use inner function

2019-12-20 10:12 UTC, whichfinder commented on src/tests/test_login.py
> +        assert main_page.wait_for_confirm_message()
use unitttest asserts

2019-12-20 10:12 UTC, whichfinder commented on src/tests/test_login.py
> +        last_name = fake.last_name()
create separate method for generating fake data

2019-12-20 10:12 UTC, whichfinder commented on src/tests/test_login.py
> +        main_page.specify_search(Keys.ENTER)
don't use inside tests

2019-12-20 10:12 UTC, whichfinder commented on src/tests/test_login.py
> +        api_helper.do_post_request(os.path.join(Config.api_host, Config.api_get_workers_id_url), body)
move path generation to __init__ in api_helper

2019-12-20 10:12 UTC, whichfinder commented on src/tests/test_login.py
> +        login_page.specify_pass(self.password)
create separate method for login

2019-12-20 10:12 UTC, whichfinder commented on src/tests/test_login.py
> +        time.sleep(5)
remove

2019-12-20 16:25 UTC, whichfinder requested changes

2019-12-20 16:25 UTC, whichfinder commented on src/tests/test_login.py
> +        LoginTestSuite.login(self)
self.login()

2019-12-20 16:25 UTC, whichfinder commented on src/tests/test_login.py
> +        main_page.enter_last_name(LoginTestSuite.generate_fake_data()["last_name"])
wtf?
some_data = self.generate_fake_data()
....
main_page.enter_first_name(some_data['first_name'])

2019-12-20 16:25 UTC, whichfinder commented on src/tests/test_login.py
> +        new_email = LoginTestSuite.generate_fake_data()["email"]
same

2019-12-20 16:25 UTC, whichfinder commented on src/tests/test_login.py
> +                                                LoginTestSuite.generate_fake_data()["last_name"])
same

2019-12-20 16:25 UTC, whichfinder commented on src/tests/test_login.py
> +                'lastname': LoginTestSuite.generate_fake_data()["last_name"]
same

2019-12-23 13:40 UTC, whichfinder approved these changes

2019-12-23 13:40 UTC, merged