Api helper
whichfinder/automation_study pull request #8
Opened 2019-11-14 11:04 UTC by dimahadgi

2019-11-14 11:20 UTC, whichfinder requested changes

2019-11-14 11:20 UTC, whichfinder commented on api_conf.ini
> +password = password
shouldn't be stored on github

2019-11-14 11:20 UTC, whichfinder commented on api_conf.ini
> +get_url =  https://acme.qc2.blnsearch.net/api-employer/workers?sort=created&order=desc&$limit=1000
set host url, path should be stored in method or class

2019-11-14 11:20 UTC, whichfinder commented on src/for_testing.py
> +print(api_help.auth_token)
add this as test, not as separate module

2019-11-14 11:20 UTC, whichfinder commented on src/utils/api_helper.py
> +        response = requests.get(get_url, headers={
create headers inside __init__

2019-11-14 11:20 UTC, whichfinder commented on src/utils/api_helper.py
> +        response = requests.get(get_url, headers={
so you can use them as headers=self.headers in all requests

2019-11-14 11:20 UTC, whichfinder commented on src/utils/certificates_generator.py
> +                                   'password': "password"})
move to config

2019-11-14 11:20 UTC, whichfinder commented on src/utils/certificates_generator.py
> +            'issued': "2017-11-05T16:01:38.433Z",
I think this is being changed from request to request

2019-11-14 11:20 UTC, whichfinder commented on src/utils/certificates_generator.py
> +GET_URL = "https://acme.qc2.blnsearch.net/api-employer/workers?sort=created&order=desc&$limit=1000"
you've set the same in config

2019-11-14 11:20 UTC, whichfinder commented on src/utils/certificates_generator.py
> +do_post_request()
do this in if name = main

2019-11-14 11:20 UTC, whichfinder commented on src/utils/certificates_generator.py
> +def do_post_request():
this method should be generic not bounded to get_worker_id

2019-11-19 15:02 UTC, whichfinder requested changes

2019-11-19 15:02 UTC, whichfinder commented on src/utils/api_helper.py
> +        self.auth_url = Config.api_test_host + Config.api_test_auth_path
os.path.join

2019-11-19 15:02 UTC, whichfinder commented on src/for_testing.py
> +print(ApiHelper().auth_get_token())
remove this module

2019-11-19 15:02 UTC, whichfinder commented on src/utils/api_helper.py
> +                                       'identifier': "{}".format(self.login),
remove format, use values

2019-11-19 15:02 UTC, whichfinder commented on src/utils/api_helper.py
> +                                       'password': "{}".format(self.password)})
same

2019-11-19 15:02 UTC, whichfinder commented on src/utils/api_helper.py
> +        response = requests.get(get_url, headers={
headers should be in init

2019-11-19 15:02 UTC, whichfinder commented on src/utils/api_helper.py
> +            'Authorization': 'bln type=session,version=1,token="{}"'.format(self.auth_token())}, json=body)
same here

2019-11-19 15:02 UTC, whichfinder commented on src/utils/certificates_generator.py
> +    def add_certificates(self):
this method will be used inside tests, so it should return something, right?

2019-11-19 15:02 UTC, whichfinder commented on src/utils/certificates_generator.py
> +                print(response.status_code)
remove print, 
We will use logger later

2019-11-19 15:02 UTC, whichfinder commented on src/utils/certificates_generator.py
> +    c.add_certificates()
rename "c" to something meaningful

2019-11-19 15:15 UTC, dimahadgi commented on src/for_testing.py
> +print(ApiHelper().auth_get_token())
added to git ignore

2019-11-22 09:40 UTC, whichfinder approved these changes

2019-11-22 09:40 UTC, merged